<template>

   <div class="row p-4 h-100">
    <div class="col-4 h-100 p-2 offset-2">
      <div class="row h-100">
       <div class="col-12 h-100" style="overflow: hidden;">
        <div class="layoutbox rounded h-100" style="overflow: hidden; display: flex; flex-flow: column;">
          <div class="text-white p-2 h3 layoutbox-title w-100 background-primary">
            {{ $t('settings.wiring') }}
            <button @click="uploadYAML" type="button" class="btn btn-danger float-right">
              <span v-if="!busy">{{ $t('settings.save') }}</span>
              <i v-else class="fa fa-spin fa-stroopwafel"></i>
            </button>
          </div>

          <!--
  In this div the peripheral selection functionality is provided.
  It makes use of the vue b-table tag, and models the 'items' field in the local data.
  In the head of the table, a b-dropdown element is generated and filled with options with v-for for
  every peripheral defined in the data.peripherals field (which is defined by a json data file provided
  and generated by the peripheral manager).
  The rows of the table are predefined by the data.field, and its coloms are peripheral 'items'
  that are added to the table with the b-dropdown. The first row is a identifier with a delete
  button, the second row is a field where a name has to be entered, and the third row is where
  pins (and later maybe additional properties) can be set.
          -->

          <div class="h-100" style="overflow-y: auto;">
            <b-table striped hover :fields="fields" :items="items">

              <template #head(type)="data">
                <div>
                  <b-dropdown id="dropdown-1" :text="$t('settings.add')" class="m-md-2">
                    <b-dropdown-item v-for="i in Object.keys(peripherals)" ref="i" @click="add_item(i)">
                      {{ $t('peripherals.' + peripherals[i].text) }}
                    </b-dropdown-item>
                  </b-dropdown>
                </div>
              </template>

              <template #cell(type)="data">
                <button @click="delete_item(data.index)" type="button" class="btn float-left">
                  <span class="fa fa-trash"> </span>
                </button>
                {{ $t('peripherals.' + peripherals[data.item.type].text) }}
              </template>

              <template #cell(name)="data">
                <b-form-input v-model="data.item.name" :placeholder="$t('settings.placeholder')"></b-form-input>
              </template>

              <template #cell(pins)="data">

                <b-form-select v-for="p in Object.keys(peripherals[data.item.type].pins)" v-model="data.item[p]"
                               :options="getValidPinBinds(data.item.type, p)">
                  <template #first>
                    <b-form-select-option :value="null" disabled>{{ p }}</b-form-select-option>
                  </template>
                </b-form-select>
                <div v-if="peripherals[data.item.type].has_frequency">
                  <p>Frequency</p>
                  <b-form-input v-model="data.item.frequency" type="number" placeholder="10"></b-form-input>
                </div>
              </template>

            </b-table>

          </div>

       </div>
      </div>


      </div>

    </div>


    <div class="col-4 h-100 p-2">
      <div class="row">
        
        <div class="col-12">

          <div class="layoutbox rounded">

          <div class="text-white p-2 h3 layoutbox-title w-100 background-primary">
            {{ $t('settings.microcontroller') }}
            <button @click="uploadMCU" type="button" class="btn btn-danger float-right">
              <span v-if="!busy">{{ $t('settings.upload') }}</span>
              <i v-else class="fa fa-spin fa-stroopwafel"></i>
            </button>
          </div>

        <div class="layoutbox-content">
          <div class="row">
              <b-form-radio v-model="mcu" value="stm32" data-label="STM32">
                Robotdyn STM32 Black Pill (arduino bootloader)
              </b-form-radio>
          </div>
          <div class="row">
              <b-form-radio v-model="mcu" value="nano" data-label="Arduino Nano">
                Arduino Nano
              </b-form-radio>
          </div>
          <div class="row">
              <b-form-radio v-model="mcu" value="nano_old" data-label="Arduino Nano (old bootloader)">
                Arduino Nano (old bootloader)
              </b-form-radio>
          </div>
          <div class="row">
              <b-form-radio v-model="mcu" value="uno" data-label="Arduino Uno)">
               Arduino Uno
              </b-form-radio>
          </div>
         </div>

         </div>
       </div>



      </div>

      <div class="row">
         <Network/>
      </div>
    </div>


</div>
</template>

<script>

import ROSLIB from 'roslib'
import YAML from 'js-yaml'
import properties_ph from "../assets/json/properties_ph.json"
import properties_mc from "../assets/json/properties_mc.json"
import Network from '@/components/Network.vue'

export default {
  components: {
    Network
  },
  data: function () {
    return {
      peripherals: properties_ph,
      microcontrollers: properties_mc,
      board: 'breadboard',
      mcu: "stm32",
      fields: [
        {key: 'type', label: 'type'},
        {key: 'name', label: 'Naam'},
        {key: 'pins', label: 'Pins'}
      ],
      items: this.$store.getters.getPConfig,
      busy: false,
      password: null
    }
  },

  methods: {
    // To add and delete items (delete_item() see below) from the peripheral configuration table
    add_item(type, name, pins) {
      var binds = {}
      if (pins){
         binds = pins;
      } else {
         binds = {...this.peripherals[type].pins}
         Object.keys(binds).forEach(function (key) {
           binds[key] = null
         })
      }
      this.items.push(Object.assign({
            type: type,
            name: name,
            rel_path: this.peripherals[type].rel_path,
            functions: this.peripherals[type].functions
          },
          binds
      ))
    },
    delete_item(index) {
      this.items.splice(index, 1)
    },
    // Depending on selected microcontroller gives peripheral configuration table valid pin binds
    getValidPinBinds(type, pin) {
      let pinMap = Object.entries({...this.microcontrollers[this.mcu].pin_map})
      if (this.peripherals[type].pins[pin] === "analog") {
        pinMap = pinMap.filter(([_, value]) => value >= this.microcontrollers[this.mcu].analog_offset)
      }
      const options = []
      for (let p of pinMap) options.push({value: p[0], text: p[0]})
      return options
    },
    // Load the configuarion from ROS params to Vue object items
    loadConfiguration(rosparams){
      this.items = []
      for (var j in rosparams){
	 if (j == "device"){
            this.mcu = rosparams['device']['mirte']['mcu'];
         } else {
	    for (var k in rosparams[j]){
               if(j == "motor"){
                 this.add_item("motor_" + rosparams[j][k]['type'], k, rosparams[j][k]['pins']);
               } else {
                 this.add_item(j, k, rosparams[j][k]['pins']);
               }
            }
         }
      }
    },
    // Should be using generateYAML() as soon as we move to the plugin manager
    saveConfiguration(){
       var tthis = this
       tthis.params_busy = true;
       var restructured = {device: {}};
       restructured['device']['mirte'] = {type: this.board, mcu: this.mcu };
       for (var j in this.items){
          var i = Object.assign({}, this.items[j]);
          var type = i['type'];
          i['device'] = 'mirte';
          delete i['type'];
          var newtype = type;
          if (type == 'motor_l9110s'){
             i['type'] = "l9110s"
             newtype = "motor"
          }
          if (type == 'motor_l298n'){
             i['type'] = "l298n"
             newtype = "motor"
          }
          if (this.board == "mirte_pcb"){
             delete i['pins']
          } else {
             delete i['connector']
          }
          
          // Add pins to pins sub
          i['pins'] = {}
          for (var k in i){
             if (k != "name" && k != "rel_path" && k != "functions" && k != "device" && k != "pins" && k != "device" && k != "type" && k!="frequency"){
                i['pins'][k] = i[k]
                delete i[k]
             }
          }

          if (!restructured.hasOwnProperty(newtype)){
             restructured[newtype] = {};
          }
          restructured[newtype][i['name']] = i;
       }
       var henk = YAML.load(JSON.stringify(restructured));
       return henk;
    },
    // Constructs the YAML file to be used and uploaded to ROS as its params
    generateYAML() {
      const yaml = {
        name: 'Mirte',
        type: this.board,
        mcu: {
          type: this.mcu,
          max_pwm_value: this.microcontrollers[this.mcu].max_pwm_value,
          analog_offset: this.microcontrollers[this.mcu].analog_offset
        },
        peripherals: {}
      }
      for (const item of this.items) {
        yaml.peripherals[item.name] = {
          super_type: this.peripherals[item.type].rel_path.split("\\")[0],
          abstract_type: this.peripherals[item.type].rel_path.split("\\")[1],
          peripheral_type: item.type,
          pin_binds: {}
        }
        for (let key in this.peripherals[item.type].pins) {
          yaml["peripherals"][item.name].pin_binds[key] = item[key]
        }
      }
      // In memory of Henk. He shall always be in our memory. Persistent through and through, until the end.
      return YAML.load(JSON.stringify(yaml))
    },
    // Requests from the server to update the ROS params with the generated YAML file of the configured Peripherals
    uploadYAML() {
      if (confirm(this.$i18n.t('settings.save_confirm'))) {
        this.busy = true
        var yaml = this.saveConfiguration();
        console.log(yaml);

        fetch(`http://${location.hostname}:3000/api/settings`, {
          method: 'POST',
          body: YAML.dump(yaml)
        })
            .then(res => res.text())
            .then(data => {
              console.log(data)
              this.busy = false
              this.$store.dispatch('setPConfig', this.items)
            })
      }
    },

    //Old out of scope server request functions
    uploadMCU() {
      if (confirm(this.$i18n.t('settings.upload_confirm'))) {
        this.busy = true
        var body = {};
        body["mcu"] = this.mcu;
        fetch(`http://${location.hostname}:3000/api/upload_telemetrix`, {
           method: 'POST',
           body: JSON.stringify(body) 
        } )
            .then(res => res.text())
            .then(data => {
              console.log(data)
              this.busy = false

              if (data.toLowerCase().includes("download done")) {
                alert("Uploaden is succesvol afgerond")
              } else {
                alert("Er is een fout opgetreden:\n\n" + data)
              }

            })
      }
    },
    setPassword() {
      if (confirm('Weet je zeker dat je het wachtwoord wilt veranderen?')) {
        fetch(`http://${location.hostname}:3000/api/passwd`, {
          method: 'POST',
          headers: {
            'Content-Type': 'text/plain',
            'CORS': 'Access-Control-Allow-Origin'
          },
          body: this.password + "\n",
        })
            .then(res => res.json())
            .then(data => {
              console.log(data)
            })
      }
    }
  },

  mounted() {
     const ros_protocol = (location.protocol === 'https:') ? 'wss://' : 'ws://'
     const ros_socketUrl = `${ros_protocol}${location.hostname}/ws/ros`
    
     var ros = new ROSLIB.Ros({
       url: ros_socketUrl
     })
    
     var params = new ROSLIB.Param({
       ros: ros,
       name: '/mirte'
     })
    
     params.get((res) => {
       this.loadConfiguration(res);
     })
  }
}
</script>
